CREATE TABLE kt_customer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    cpf        VARCHAR(255)                            NOT NULL,
    income     NUMERIC(10,2)                           NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    zip_code   VARCHAR(255)                            NOT NULL,
    street     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_kt_customer PRIMARY KEY (id)
);

ALTER TABLE kt_customer
    ADD CONSTRAINT uc_kt_customer_email UNIQUE (email);

ALTER TABLE kt_customer
    ADD CONSTRAINT uc_kt_customer_password UNIQUE (password);